spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F://日志
#  file: F://日志/sell.log
#  level:
#    com.imooc.LoggerTest: debug

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mpAppId: wxd898fcb01713c658
  mpAppSecret: xxxxxxxxx #借用号appId,appSecret
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #开放平台测试号appId,appSecret
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #借用帐号appId,appSecret
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: C:/Users/Administrator/Downloads/h5.p12
  notifyUrl: http://sqmax.natapp1.cc/notify
  templateId:
    orderStatus: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

projectUrl:
  wechatMpAuthorize: http://sqmax.natapp1.cc
  wechatOpenAuthorize: http://sqmax.natapp1.cc
  sell: http://sqmax.natapp1.cc
